### ISSUE TITLE
Line ending issue: CRLF / LF

### ISSUE THREAD

**Issue by shouldsee** [CATH-summer-2017/domchop-pymol#10]
@ilsenatorov 
It might be worth documenting the struggle with line ending into a blog so that we don't get confused next time.

**Comment by ilsenatorov** [comment]
@shouldsee agreed

**Comment by ilsenatorov** [comment]
[this page](https://help.github.com/articles/dealing-with-line-endings/ "Git line endings") has the info about the line-endings and how to deal with them
