### ISSUE TITLE
Name as .pml 

### ISSUE THREAD

**Issue by ilsenatorov** [CATH-summer-2017/domchop-pymol#8]
right now code works if you rename it as .pml

**Comment by ilsenatorov** [comment]
@shouldsee do you know how to make CGI name files? right now it downloads the file with the name of the script (display_pymol.py) and I can't find info about how to change it.

**Comment by shouldsee** [comment]
Supposedly you are dealing with a GET request, to which you need to return a HTTP response. 

say you are issuing a GET request at http://localhost/blah/display_pymol.py using a client (like chrome), then whatever the client receives from the server will be dumped into "display_pymol.py" if a default filename is not specified. Similarly if your change the URL to http://localhost/blah/dpymol.py then the filename will default to "dpymol.py".

There seems to be a way to suggest a filename in your response but I am still searching for it.

UPDATE:
It may be worthy to try "Content-Disposition" on top of "Content-Type"

e.g.:

```http
Content-Type: application/json; charset=utf-8;
Content-Disposition: attachment;  filename="1pkmA01.json"
Content-Disposition: attachment;  filename=1pkmA01.json  ##### (No Quotes? Haven't tried yet)

```

Ref: https://www.jmarshall.com/easy/http/#sample

**Comment by ilsenatorov** [comment]
solved, filename has to be without quotes
