### ISSUE TITLE
+ and URL

### ISSUE THREAD

**Issue by ilsenatorov** [CATH-summer-2017/domchop-pymol#9]
Since the string has spaces and + signs in it and URL treats plus as space, + signs need to be substituted with %2B before creating the string or code needs to be changed

**Comment by shouldsee** [comment]
can you point me to the relevant piece of code? Might be worth using "urllib.urlencode" to construct url, which automatically handle "space" or "+".

```python
import urllib
urllib.urlencode({'foo': 'bar', 'bla': 'blah'})
foo=bar&bla=blah

the_str='10gsA D2-78[A]+187-208[A] D79-186[A] F209-209[A]'
urllib.urlencode( { 'data' : the_str } )
'data=10gsA+D2-78%5BA%5D%2B187-208%5BA%5D+D79-186%5BA%5D+F209-209%5BA%5D'

```

**Comment by ilsenatorov** [comment]
@shouldsee, it is just a general problem that arises due to string in CATH having spaces and a plus in it. I mean on line 12 in create_pml.py in the CGI branch it takes the value from the CGI, which you write in the form of "http://localhost/cgi-bin/display_pymol.py?what_string=" with the string after the "=". then using regex script takes out the info about domains and fragments

**Comment by shouldsee** [comment]
Try
```python
import urllib
the_str='10gsA D2-78[A]+187-208[A] D79-186[A] F209-209[A]'
print "http://localhost/cgi-bin/display_pymol.py?" + urllib.urlencode( { 'what_string' : the_str } )

"http://localhost/cgi-bin/display_pymol.py?what_string=10gsA+D2-78%5BA%5D%2B187-208%5BA%5D+D79-186%5BA%5D+F209-209%5BA%5D"
```

It's common practice to encode URL with '%blah' to avoid problem parsing '/','?','=' (cuz these symbols have special meaning in URL, e.g.: to specify parameters of a [GET request](https://www.w3schools.com/tags/ref_httpmethods.asp) )'

It's also possible to extract GET params from a url using "urlparse"
Pasted from [stackoverflow](https://stackoverflow.com/questions/5074803/retrieving-parameters-from-a-url)
```python
import urlparse
url = 'http://example.com/?q=abc&p=123'
par = urlparse.parse_qs(urlparse.urlparse(url).query)

print par['q'], par['p']
['abc'] ['123']
```

**Comment by ilsenatorov** [comment]
solved, CATH already uses URL code that works
